services:
  web:
    build: .
    command: gunicorn gradecheck.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DJANGO_DEBUG=False
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - backend

volumes:
  static_volume:

networks:
  backend:
